 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'gcr.io/finalproject-338303/backend_service', '--build-arg=JAR_FILE=target/musicplayer-0.0.1-SNAPSHOT.jar', '.']
   images: ['gcr.io/finalproject-338303/backend_service']